language: python
dist: xenial
sudo: true
python:
  - 3.8

services: postgresql

addons:
  postgresql: "9.5"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - cp contrib/env-sample .env
  - pip install pipenv
  - pipenv sync --dev

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - pipenv run flake8
  - pipenv run python src/manage.py test
