version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./contrib/nginx:/etc/nginx/conf.d
      - static_volume:/srv/www/static
      - media_volume:/srv/www/media
    depends_on:
      - app_gestao

  app_gestao:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - "static_volume:/app/static"
      - "media_volume:/app/media"
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DEBUG: "${DEBUG}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
      DATABASE_URL: "${DBURL}"
      TIME_ZONE: "${TIME_ZONE}"
      LANGUAGE_CODE: "${LANGUAGE_CODE}"
      CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${DBNAME}"
      POSTGRES_USER: "${DBUSER}"
      POSTGRES_PASSWORD: "${DBPASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
