version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./contrib/nginx:/etc/nginx/conf.d
      - static_volume:/srv/www/static
      - media_volume:/srv/www/media
    depends_on:
      - uwsgi

  uwsgi:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB="${DATABASE_NAME}"
      - POSTGRES_USER="${DATABASE_USER}"
      - POSTGRES_PASSWORD="${DATABASE_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  volumes:
    postgres_data:
    static_volume:
    media_volume:
