version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./contrib/nginx:/etc/nginx/conf.d
      - static_volume:/srv/www/static
      - media_volume:/srv/www/media
    depends_on:
      - app_gestao

  app_gestao:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - "static_volume:/app/static"
      - "media_volume:/app/media"
    env_file:
      - ./.env
    depends_on:
      - db

  celery:
    build:
      context: .
    env_file:
      - ./.env
    command: >
      celery -A gestao_rh worker -l info -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - app_gestao

  db:
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
