# Generated by Django 3.1.1 on 2020-09-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20200829_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
