# Generated by Django 3.1 on 2020-08-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=80)),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
            ],
        ),
    ]
