# Generated by Django 3.1 on 2020-08-29 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
            preserve_default=False,
        ),
    ]
