name: CI
on:
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install pipenv
          pipenv --python 3.8
          pipenv sync
          pipenv sync --dev
      - name: Run Lint
        run: pipenv run flake8
      - name: Run Coverage
        run: |
          cp contrib/env-sample ./.env
          cd src/
          pipenv run coverage run manage.py test
          pipenv run coverage xml

