name: CI
on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Pipenv
        run: |
          python -m pip install pipenv
          pipenv --python 3.8
      - name: Cache Python Dependencies
        uses: actions/cache@v2
        id: cache-pipenv
        with:
          path: ~/.local/share/virtualenv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: |
          pipenv sync
          pipenv sync --dev
      - name: Run Lint
        run: pipenv run flake8
      - name: Run Coverage
        run: |
          cp contrib/env-sample ./.env
          cd src/
          pipenv run coverage run manage.py test
          pipenv run coverage xml
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: gestao-rh
    steps:
      - uses: actions/checkout@v2
      - name: Release Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: vespene/django-gestao-rh/${{ env.CONTAINER_NAME }}
          push: true
          tags: latest
          tag_with_ref: true
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: julinux/${{ env.CONTAINER_NAME }}
          push: true
          tags: latest
          tag_with_ref: true


