name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv --three
          pipenv sync
          pipenv sync --dev
      - name: Lint with flake8
        run: pipenv run flake8
  run_coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
      PIPENV_VENV_IN_PROJECT: 1
      SECRET_KEY: ${{ secrets.CODECOV_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Generate coverage report
      run: |
        cp contrib/env-sample ./.env
        python -m pip install pipenv
        pipenv --python 3.8
        pipenv sync
        pipenv sync --dev
        cd src/
        pipenv run coverage run manage.py test
        pipenv run coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./src/coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./src/coverage.xml
